.\" Manpage for mshar.
.\" 
.\" CC0
.\" To the extent possible under law, MXPSQL has waived all copyright and related or neighboring rights to Documentation for MShar. This work is published from: Indonesia.

.TH man 7 "31 March 2022" "No Version It's a rolling release" "mshar man page"
.SH NAME
mshar \- MXPSQL's version of the shell archiver (shar)

.SH SYNOPSIS
mshar <mode> [whatever depending on the mode]

mshar update-self

mshar make-archive yourarchive.mshar yourcode.cpp nintendogames.tar.gz mariokartwii.iso

mshar noop

The texinfo document will be maintained more than the man page

.SH DESCRIPTION
A better shell archiver that needs base64 to run lmao

It will output a shell script that will extract itself.

Can self update itself (if you have git and the place where it is located is actually a git repository)

Contains an API for creating archives

.SH OPTIONS
mshar <mode> [whatever]
Modes:

	all of these args are after the mode args

	update-self (only work if you git cloned it): no args

	make-archive: <archive file> [<your file> ...]

	noop: does nothing (useful for sourcing)

	version: gives you the Version

	help: tells you to run mshar without args

.SH BUGS
No known bugs lol

.SH AUTHOR
MXPSQL (I am not telling you my real name)
